version: 2.1 # use CircleCI 2.0

defaults: &defaults
  environment: &environment
    CIRCLE_TEST_REPORTS: /tmp/test-results
    CIRCLE_ARTIFACTS: /tmp/test-artifacts
    BUNDLE_JOBS: 4
    BUNDLE_RETRY: 3
    BUNDLE_PATH: ~/spree/vendor/bundle
    RAILS_VERSION: '~> 7.1.0'
  working_directory: ~/spree
  docker:
    - image: &ruby_3_2_image circleci/ruby:3.0-node-browsers
    - image: &redis_image circleci/redis:6.2-alpine

run_tests_3_2: &run_tests_3_2
  <<: *defaults
  parallelism: 8
  steps:
    - checkout
    - restore_cache:
        keys:
          - spree-storefront-old-bundle-v10-ruby-3-2-{{ .Branch }}
          - spree-storefront-old-bundle-v10-ruby-3-2
    - run:
        name: Add keyserver
        command: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4EB27DB2A3B88B8B
    - run:
        name: Install libvips
        command: sudo apt-get update && sudo apt-get install libvips
    - run:
          name: Set bundle path
          command: bundle config --local path vendor/bundle
    - run:
          name: Ensure bundle Install
          command: |
            bundle check || bundle install
    - run:
        name: Create test app
        command: |
          bundle exec rake test_app
    - run:
          name: Run Rspec
          command: |
            TESTFILES=$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
            bundle exec rspec --format documentation \
                              --format RspecJunitFormatter \
                              -o ~/rspec/rspec.xml \
                              -- ${TESTFILES}
    - store_test_results:
          path: ~/rspec
    - store_artifacts:
          path: tmp/capybara

jobs:
  bundle_ruby_3_2:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - spree-storefront-old-bundle-v10-ruby-3-2-{{ .Branch }}
            - spree-storefront-old-bundle-v10-ruby-3-2
      - run:
          name: Add keyserver
          command: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4EB27DB2A3B88B8B
      - run:
          name: Install libvips
          command: sudo apt-get update && sudo apt-get install libvips
      - run:
          name: Set bundle path
          command: bundle config --local path vendor/bundle
      - run:
          name: Bundle Install
          command: |
            bundle check || bundle install
      - save_cache:
          paths:
            - vendor/bundle
          key: spree-storefront-old-bundle-v10-ruby-3-2-{{ checksum "Gemfile.lock" }}

  tests_ruby_3_2_rails_7_1_postgres:
    <<: *run_tests_3_2
    environment: &postgres_environment
      <<: *environment
      DB: postgres
      DB_HOST: localhost
      DB_USERNAME: postgres
    docker:
      - image: *ruby_3_2_image
      - image: &postgres_image circleci/postgres:12-alpine
        environment:
          POSTGRES_USER: postgres
      - image: *redis_image

  tests_ruby_3_2_rails_7_1_mysql:
    <<: *run_tests_3_2
    environment: &mysql_environment
      <<: *environment
      DB: mysql
      DB_HOST: 127.0.0.1
      DB_USERNAME: root
      COVERAGE: true
      COVERAGE_DIR: /tmp/workspace/simplecov
    docker:
      - image: *ruby_3_2_image
      - image: *redis_image
      - image: &mysql_image circleci/mysql:8-ram

workflows:
  version: 2
  main:
    jobs:
      - bundle_ruby_3_2
      - tests_ruby_3_2_rails_7_1_postgres:
          requires:
            - bundle_ruby_3_2
      - tests_ruby_3_2_rails_7_1_mysql:
          requires:
            - bundle_ruby_3_2
